<Project>
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Authors>Tesearis.DotNetAssemblyQuery contributors</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/marek-jelo-jelinek/dotnet-assembly-query</PackageProjectUrl>
    <RepositoryUrl>https://github.com/marek-jelo-jelinek/dotnet-assembly-query</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright (c) 2026 Marek Jelínek</Copyright>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts/</PackageOutputPath>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
